sed -i 's/soc_mmio/csx_mmio/g' source/soc.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_cfg.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_dpll.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_gp_timer.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_mpu.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_mpu_gpio.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_mpu_ihr.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_mpu_mmc.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_ocp.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_os_timer.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_timer.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_uart.h
sed -i 's/soc_mmio/csx_mmio/g' include/csx_mmio_watchdog.h
